import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import { NextAuthProvider } from "@/server/provider/nextAuthProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import PaypalProvider from "../features/paypal/PaypalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <PaypalProvider>
        <body className={inter.className}>
          <NextAuthProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </NextAuthProvider>
          <ToastContainer autoClose={3000} />
        </body>
      </PaypalProvider>
    </html>
  );
}
